version: "3.8"
services:
 mysql-container:
  image: mysql:8
  #container_name: mysql-container
  environment:
   MYSQL_ROOT_PASSWORD: root123
   MYSQL_DATABASE: employee_db
  ports:
  - "3307:3306"
  restart: always
 spring-boot-container:
  build: ./
  #image: akashkale/spring-boot-container:v1
  #container_name: spring-boot-container
  depends_on: 
   - mysql-container
  ports:
   - "8080:8080"
  restart: always