var id = 100;
//id="Steven";
var fname = "Raj Deep";
var result = true;
var msg = 100;
msg = "Welcome to TS";
console.log("id is " + id);
console.log("name is " + fname);
console.log("result is " + result);
console.log("msg is " + msg);
